apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
  labels:
    app: wazuh-manager
  name: wazuh
  namespace: wazuh
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: api
    nodePort: 32322
    port: 55000
    protocol: TCP
    targetPort: 55000
  - name: registration
    nodePort: 30653
    port: 1515
    protocol: TCP
    targetPort: 1515
  selector:
    app: wazuh-manager
    node-type: master
  type: NodePort
