apiVersion: v1
kind: Service
metadata:
  labels:
    app: wazuh-manager
  name: wazuh-cluster
  namespace: wazuh
spec:
  ports:
  - name: cluster
    port: 1516
    protocol: TCP
    targetPort: 1516
  selector:
    app: wazuh-manager
  type: ClusterIP
