apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-namespace.yaml
  - 01-storageclass.yaml
  - 10-configmap-dashboard.yaml
  - 11-configmap-indexer.yaml
  - 12-configmap-manager.yaml
  - 20-service-dashboard.yaml
  - 21-service-indexer.yaml
  - 22-service-manager.yaml
  - 23-service-cluster.yaml
  - 24-service-indexer-cluster.yaml
  - 25-service-workers.yaml
  - 30-statefulset-indexer.yaml
  - 31-statefulset-master.yaml
  - 32-statefulset-worker.yaml
  - 40-deployment-dashboard.yaml
