apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: glpi
  namespace: glpi
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "64m"
    cert-manager.io/cluster-issuer: internal-ca-issuer
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - glpi.local
      secretName: glpi-tls
  rules:
    - host: glpi.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: glpi
                port:
                  number: 80
